### ISSUE TITLE
hタグのline-height調整

### ISSUE THREAD

**Issue by norikogondo** [norikogondo/portfolio#3]
Bodyを全てline-height:2 にしているせいで、hタグの見出しもそうなっていて、見出しが改行された時間延びしちゃっているのを修正。
Bodyを全てline-height:2 のままで、hタグだけline-height:1.2 にしたい。

**Comment by Mizzuu** [comment]
見出しってどれ？

**Comment by norikogondo** [comment]
https://norikogondo.com/sephora/
<img width="1512" alt="Screen Shot 0005-03-09 at 5 10 30 PM" src="https://user-images.githubusercontent.com/76888385/224197584-1273309b-66fe-4e20-9240-48d217a1a741.png">

**Comment by ShuSgw** [comment]
On dev
